### ISSUE TITLE
squantorPcbLibrary shouldn't be in templates?

### ISSUE THREAD

**Issue by fdamstra** [Squantor/templates_kicad#1]
Thank you very much for sharing these!

I noticed two things:
1) The `squantorPcbLibrary` probably shouldn't be in the templates directory. If it is there, then when you go to File->New->Project from template, KiCad gives an error: "can't open file '{templatepath}\squantorPcbLibrary\meta\info.html`.
2) That library must exist in the parent directory of the templates directory. I'm not sure why this is. Maybe your templates path is a subdirectory of your libraries path? I don't know.

Regardless, to solve both problems, after running `git submodule update`, I had to run `mv squantorPcbLibrary ..`.

**Comment by Squantor** [comment]
Hello fdamstra,

1. Indeed, I seem have to forgotten to check in some files on the ```squantorPcbLibrary``` submodule that will supress this error. It is still not pretty getting a template that is not a template. I will add these files when I get home.
2. There a few reasons I have included my private library ```squantorPcbLibrary``` in my templates is that some of the templates use components from that library. Next to that, when instantiating new projects from a template I generally keep the library ```squantorPcbLibrary``` into the same directory, so all the paths that are in ```sym-lib-table``` and ```fp-lib-table``` remain consistent and do not break. This makes the template directory really strongly bound to my way of working and not really portable. I have not found a workaround for this problem without breaking the instantiation of projects via templates in kicad. 

One big reason I use templates is that I preprogram a few board house design rules in my template and add a versionnumber and openhardware logo in my project. Next to that I also draw a board outline if the template is meant to fit a project box. Kicad does not support board outline PCB components (yet) so if I do not want to redraw the board outline every time I am forced to use a template.

One workaround would be to include the used components into the project itself but I dislike that duplication of components, making component versions/changes inconsistent in between templates.

**Comment by Squantor** [comment]
I have added a commit that will supress the error by adding a meta directory to ```squantorPcbLibrary```, but now it will show up as a template that is not really a template.
